spring:
  application:
    name: smartmarket-api
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
management:
  endpoints:
    web:
      exposure:
        include: health, info
springdoc:
  webjars:
    prefix: ""
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
logging:
  level:
    org:
      springframework:
        cache: TRACE
server:
  error:
    include-stacktrace: on_param
api:
  config:
    security:
      token:
        issuer: ${JWT_ISSUER}
        audience: ${JWT_AUDIENCE}
        secret: ${JWT_SECRET}
        access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:30m}
        refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1d}
    rabbitmq:
      exchange: smartmarket-exchange
      scraper:
        data:
          queue: scraper-data-queue
        control:
          routing-key: scraper-control-routing-key